server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yk_bike?allowPublicKeyRetrieval=true&&useUnicode=true&&characterEncoding=utf8&&useSSL=false&&autoReconnect=true&&serverTimezone=Asia/Shanghai
    username: root
    password: root

  application:
    name: YKBikeServer
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
